import {
  Clock, Cloud, Rss, BarChart3, Play, ScrollText, Building2,
  TrendingUp, Presentation, QrCode, Image, Type, CalendarDays, Film,
  Timer, BarChart2, Globe, Images, ListVideo, Ticket, Zap
} from 'lucide-react'

export const WIDGET_CATALOG = [
  {
    type: 'clock',
    label: 'Horloge',
    icon: Clock,
    description: 'Heure et date en temps réel',
    defaultSize: { w: 280, h: 160 },
    defaultConfig: {
      format: '24h',
      showDate: true,
      showSeconds: true,
    },
    configSchema: [
      { key: 'format', type: 'select', label: 'Format', options: ['12h', '24h'] },
      { key: 'showDate', type: 'boolean', label: 'Afficher la date' },
      { key: 'showSeconds', type: 'boolean', label: 'Afficher les secondes' },
      { key: 'textColor', type: 'color', label: 'Couleur texte' },
      { key: 'backgroundColor', type: 'color', label: 'Fond' },
    ]
  },
  {
    type: 'weather',
    label: 'Météo',
    icon: Cloud,
    description: 'Conditions actuelles',
    defaultSize: { w: 260, h: 200 },
    defaultConfig: {
      city: 'Bruxelles',
      lat: 50.85,
      lon: 4.35,
      units: '°C',
      forecastDays: 0,
    },
    configSchema: [
      { key: 'city', type: 'text', label: 'Ville' },
      { key: 'lat', type: 'number', label: 'Latitude' },
      { key: 'lon', type: 'number', label: 'Longitude' },
      { key: 'units', type: 'select', label: 'Unité', options: ['°C', '°F'] },
      { key: 'forecastDays', type: 'slider', label: 'Jours de prévisions (0 = désactivé)', min: 0, max: 7, step: 1 },
      { key: 'textColor', type: 'color', label: 'Couleur texte' },
      { key: 'backgroundColor', type: 'color', label: 'Fond' },
    ]
  },
  {
    type: 'rss',
    label: 'Flux RSS',
    icon: Rss,
    description: 'Actualités depuis RSS',
    defaultSize: { w: 340, h: 400 },
    defaultConfig: {
      feedUrl: '',
      maxItems: 5,
      showImages: false,
    },
    configSchema: [
      { key: 'feedUrl', type: 'text', label: 'URL du flux', placeholder: 'https://...' },
      { key: 'maxItems', type: 'number', label: 'Nombre d\'articles', min: 1, max: 20 },
      { key: 'showImages', type: 'boolean', label: 'Afficher les images' },
      { key: 'accentColor', type: 'color', label: 'Couleur accent' },
      { key: 'textColor', type: 'color', label: 'Couleur texte' },
      { key: 'backgroundColor', type: 'color', label: 'Fond' },
    ]
  },
  {
    type: 'kpi',
    label: 'Indicateur KPI',
    icon: BarChart3,
    description: 'Chiffre clé avec tendance',
    defaultSize: { w: 220, h: 160 },
    defaultConfig: {
      label: 'Indicateur',
      value: '0',
      prefix: '',
      unit: '',
      trend: 'neutral',
      trendValue: '',
      target: '',
      accentColor: '#6366f1',
      valueColor: '#ffffff',
      labelColor: '#71717a',
      showAccentBorder: false,
      paddingTop: 16,
      paddingBottom: 16,
      paddingX: 16,
      rowGap: 6,
    },
    configSchema: [
      { key: 'label', type: 'text', label: 'Libellé' },
      { key: 'prefix', type: 'text', label: 'Préfixe (ex: €)' },
      { key: 'value', type: 'text', label: 'Valeur' },
      { key: 'unit', type: 'text', label: 'Suffixe (ex: %)' },
      { key: 'trend', type: 'select', label: 'Tendance', options: ['up', 'down', 'neutral'] },
      { key: 'trendValue', type: 'text', label: 'Valeur tendance (ex: +5%)' },
      { key: 'target', type: 'text', label: 'Objectif (optionnel)' },
      { key: 'accentColor', type: 'color', label: 'Couleur accent' },
      { key: 'valueColor', type: 'color', label: 'Couleur valeur' },
      { key: 'showAccentBorder', type: 'boolean', label: 'Bordure accent gauche' },
      { key: 'paddingTop', type: 'slider', label: 'Marge haut (px)', min: 0, max: 60, step: 1 },
      { key: 'paddingBottom', type: 'slider', label: 'Marge bas (px)', min: 0, max: 60, step: 1 },
      { key: 'paddingX', type: 'slider', label: 'Marge gauche/droite (px)', min: 0, max: 60, step: 1 },
      { key: 'rowGap', type: 'slider', label: 'Espacement entre lignes (px)', min: 0, max: 40, step: 1 },
    ]
  },
  {
    type: 'youtube',
    label: 'Vidéo YouTube',
    icon: Play,
    description: 'Vidéo, playlist ou court',
    defaultSize: { w: 480, h: 300 },
    defaultConfig: {
      url: '',
      autoplay: true,
      muted: true,
      loop: true,
      captions: false,
      captionsLang: 'fr',
    },
    configSchema: [
      { key: 'url', type: 'text', label: 'URL YouTube (vidéo ou playlist)', placeholder: 'https://youtube.com/watch?v=... ou ?list=...' },
      { key: 'autoplay', type: 'boolean', label: 'Lecture automatique' },
      { key: 'muted', type: 'boolean', label: 'Muet' },
      { key: 'loop', type: 'boolean', label: 'Boucle' },
      { key: 'captions', type: 'boolean', label: 'Sous-titres' },
      { key: 'captionsLang', type: 'select', label: 'Langue sous-titres', options: ['fr', 'en', 'nl', 'de', 'es'] },
    ]
  },
  {
    type: 'video',
    label: 'Vidéo locale',
    icon: Film,
    description: 'MP4/WebM depuis la bibliothèque',
    defaultSize: { w: 480, h: 300 },
    defaultConfig: {
      videoUrl: '',
      loop: true,
      muted: true,
      fit: 'cover',
    },
    configSchema: [
      { key: 'videoUrl', type: 'file', label: 'Fichier vidéo', accept: 'video' },
      { key: 'loop', type: 'boolean', label: 'Boucle infinie' },
      { key: 'muted', type: 'boolean', label: 'Muet' },
      { key: 'fit', type: 'select', label: 'Ajustement', options: ['cover', 'contain', 'fill'] },
    ]
  },
  {
    type: 'ticker',
    label: 'Bande défilante',
    icon: ScrollText,
    description: 'Texte défilant',
    defaultSize: { w: 1920, h: 56 },
    defaultConfig: {
      content: 'Bienvenue sur nos écrans',
      speed: 1,
      backgroundColor: 'rgba(10, 10, 14, 0.8)',
      textColor: '#FFFFFF',
      rssEnabled: false,
      rssUrls: '',
      alertEnabled: false,
      alertText: '',
      alertColor: '#f59e0b',
      alertBold: true,
    },
    configSchema: [
      { key: 'rssEnabled', type: 'boolean', label: 'Activer flux RSS' },
      { key: 'rssUrls', type: 'textarea', label: 'URLs RSS (une par ligne — FR, NL, EN…)', placeholder: 'https://feeds.lemonde.fr/rss/une\nhttps://feeds.rtbf.be/...', visibleIf: c => !!c.rssEnabled },
      { key: 'content', type: 'textarea', label: 'Texte libre (affiché avec/sans RSS)' },
      { key: 'alertEnabled', type: 'boolean', label: 'Message ponctuel (alerte)' },
      { key: 'alertText', type: 'text', label: 'Texte du message', placeholder: 'Réunion dans 20 minutes', visibleIf: c => !!c.alertEnabled },
      { key: 'alertColor', type: 'color', label: 'Couleur alerte', visibleIf: c => !!c.alertEnabled },
      { key: 'alertBold', type: 'boolean', label: 'Alerte en gras', visibleIf: c => !!c.alertEnabled },
      { key: 'speed', type: 'slider', label: 'Vitesse', min: 0.5, max: 3, step: 0.1 },
      { key: 'fontSize', type: 'slider', label: 'Taille texte', min: 12, max: 40, step: 1 },
      { key: 'backgroundColor', type: 'color', label: 'Fond' },
      { key: 'textColor', type: 'color', label: 'Couleur texte' },
    ]
  },
  {
    type: 'logo',
    label: 'Logo',
    icon: Building2,
    description: 'Logo entreprise',
    defaultSize: { w: 200, h: 100 },
    defaultConfig: {
      imageUrl: '',
      showName: true,
      companyName: 'Entreprise',
      showBorder: false,
    },
    configSchema: [
      { key: 'imageUrl', type: 'file', label: 'Image' },
      { key: 'showName', type: 'boolean', label: 'Afficher le nom' },
      { key: 'companyName', type: 'text', label: 'Nom de l\'entreprise' },
      { key: 'backgroundColor', type: 'color', label: 'Fond (vide = transparent)' },
      { key: 'showBorder', type: 'boolean', label: 'Afficher la bordure' },
    ]
  },
  {
    type: 'stocks',
    label: 'Bourse',
    icon: TrendingUp,
    description: 'Cours de bourse',
    defaultSize: { w: 300, h: 200 },
    defaultConfig: {
      symbols: 'BEL20, CAC40',
      refreshSeconds: 60,
    },
    configSchema: [
      { key: 'symbols', type: 'text', label: 'Tickers', placeholder: 'BEL20, CAC40' },
      { key: 'refreshSeconds', type: 'number', label: 'Rafraîchir (sec)', min: 10 },
      { key: 'accentColor', type: 'color', label: 'Couleur accent' },
      { key: 'textColor', type: 'color', label: 'Couleur texte' },
      { key: 'backgroundColor', type: 'color', label: 'Fond' },
    ]
  },
  {
    type: 'slideshow',
    label: 'Diaporama',
    icon: Images,
    description: 'Galerie d\'images avec transitions',
    defaultSize: { w: 640, h: 400 },
    defaultConfig: {
      images: [],
      intervalSeconds: 5,
      transition: 'fade',
      fit: 'cover',
      showDots: true,
      caption: '',
    },
    configSchema: [
      { key: 'images', type: 'filelist', label: 'Images du diaporama', accept: 'image' },
      { key: 'intervalSeconds', type: 'slider', label: 'Durée par image (sec)', min: 2, max: 30, step: 1 },
      { key: 'transition', type: 'select', label: 'Transition', options: ['fade', 'slide', 'zoom'] },
      { key: 'fit', type: 'select', label: 'Ajustement', options: ['cover', 'contain', 'fill'] },
      { key: 'showDots', type: 'boolean', label: 'Afficher les points' },
      { key: 'caption', type: 'text', label: 'Légende (optionnel)' },
    ]
  },
  {
    type: 'slides',
    label: 'Google Slides',
    icon: Presentation,
    description: 'Présentation embarquée',
    defaultSize: { w: 480, h: 300 },
    defaultConfig: {
      embedUrl: '',
      autoAdvance: true,
      intervalSeconds: 10,
    },
    configSchema: [
      { key: 'embedUrl', type: 'text', label: 'URL d\'intégration' },
      { key: 'autoAdvance', type: 'boolean', label: 'Avancer automatiquement' },
      { key: 'intervalSeconds', type: 'number', label: 'Intervalle (sec)', min: 5 },
    ]
  },
  {
    type: 'qrcode',
    label: 'QR Code',
    icon: QrCode,
    description: 'QR code vers URL',
    defaultSize: { w: 160, h: 160 },
    defaultConfig: {
      qrType: 'url',
      url: '',
      qrText: '',
      wifiSsid: '',
      wifiPassword: '',
      wifiSecurity: 'WPA',
      label: '',
    },
    configSchema: [
      { key: 'qrType', type: 'select', label: 'Type de QR Code', options: ['url', 'wifi', 'text'] },
      { key: 'url', type: 'text', label: 'URL cible', placeholder: 'https://...', visibleIf: c => (c.qrType || 'url') === 'url' },
      { key: 'qrText', type: 'textarea', label: 'Texte libre', visibleIf: c => c.qrType === 'text' },
      { key: 'wifiSsid', type: 'text', label: 'Nom du réseau (SSID)', visibleIf: c => c.qrType === 'wifi' },
      { key: 'wifiPassword', type: 'text', label: 'Mot de passe WiFi', visibleIf: c => c.qrType === 'wifi' },
      { key: 'wifiSecurity', type: 'select', label: 'Sécurité', options: ['WPA', 'WEP', 'nopass'], visibleIf: c => c.qrType === 'wifi' },
      { key: 'label', type: 'text', label: 'Label affiché sous le QR' },
    ]
  },
  {
    type: 'image',
    label: 'Image',
    icon: Image,
    description: 'Image statique',
    defaultSize: { w: 320, h: 240 },
    defaultConfig: {
      imageUrl: '',
      fit: 'cover',
    },
    configSchema: [
      { key: 'imageUrl', type: 'file', label: 'Image' },
      { key: 'fit', type: 'select', label: 'Ajustement', options: ['cover', 'contain', 'fill'] },
    ]
  },
  {
    type: 'text',
    label: 'Texte libre',
    icon: Type,
    description: 'Bloc de texte',
    defaultSize: { w: 300, h: 120 },
    defaultConfig: {
      content: 'Votre texte ici',
      fontSize: 16,
      fontWeight: 'normal',
      textAlign: 'left',
      verticalAlign: 'center',
      textColor: '#FFFFFF',
      backgroundColor: 'transparent',
      lineHeight: 1.4,
      letterSpacing: 0,
      textShadow: false,
    },
    configSchema: [
      { key: 'content', type: 'textarea', label: 'Contenu' },
      { key: 'fontSize', type: 'slider', label: 'Taille police', min: 10, max: 200, step: 1 },
      { key: 'fontWeight', type: 'select', label: 'Poids', options: ['normal', 'medium', 'semibold', 'bold'] },
      { key: 'textAlign', type: 'select', label: 'Alignement H', options: ['left', 'center', 'right'] },
      { key: 'verticalAlign', type: 'select', label: 'Alignement V', options: ['top', 'center', 'bottom'] },
      { key: 'textColor', type: 'color', label: 'Couleur texte' },
      { key: 'backgroundColor', type: 'color', label: 'Fond (transparent = vide)' },
      { key: 'lineHeight', type: 'slider', label: 'Interligne', min: 1, max: 3, step: 0.1 },
      { key: 'letterSpacing', type: 'slider', label: 'Espacement lettres (px)', min: -2, max: 20, step: 0.5 },
      { key: 'textShadow', type: 'boolean', label: 'Ombre portée' },
    ]
  },
  {
    type: 'calendar',
    label: 'Calendrier',
    icon: CalendarDays,
    description: 'Calendrier du mois',
    defaultSize: { w: 300, h: 280 },
    defaultConfig: { source: 'manual', maxEvents: 5, accentColor: '#fb7185' },
    configSchema: [
      { key: 'source', type: 'select', label: 'Source', options: ['manual', 'google', 'ical'] },
      { key: 'maxEvents', type: 'number', label: 'Événements max', min: 1, max: 20 },
      { key: 'accentColor', type: 'color', label: 'Couleur accent' },
      { key: 'textColor', type: 'color', label: 'Couleur texte' },
      { key: 'backgroundColor', type: 'color', label: 'Fond' },
    ]
  },
  {
    type: 'countdown',
    label: 'Compte à rebours',
    icon: Timer,
    description: 'Décompte vers un événement',
    defaultSize: { w: 480, h: 180 },
    defaultConfig: {
      title: 'Événement',
      targetDate: '',
      doneText: '🎉 C\'est parti !',
      accentColor: '#6366f1',
    },
    configSchema: [
      { key: 'title', type: 'text', label: 'Titre' },
      { key: 'targetDate', type: 'text', label: 'Date cible', placeholder: '2025-12-31T00:00:00' },
      { key: 'doneText', type: 'text', label: 'Message fin' },
      { key: 'accentColor', type: 'color', label: 'Couleur' },
    ]
  },
  {
    type: 'chart',
    label: 'Graphique',
    icon: BarChart2,
    description: 'Graphique barres, lignes ou donut',
    defaultSize: { w: 480, h: 300 },
    defaultConfig: {
      title: 'Statistiques',
      chartType: 'bar',
      data: 'Jan:120,Fév:180,Mar:150,Avr:200,Mai:175,Jun:220',
      barColor: '#6366f1',
    },
    configSchema: [
      { key: 'title', type: 'text', label: 'Titre' },
      { key: 'chartType', type: 'select', label: 'Type', options: ['bar', 'line', 'donut'] },
      { key: 'data', type: 'textarea', label: 'Données (Libellé:valeur, ...)' },
      { key: 'barColor', type: 'color', label: 'Couleur principale' },
    ]
  },
  {
    type: 'iframe',
    label: 'Page Web',
    icon: Globe,
    description: 'Intégrer n\'importe quelle URL',
    defaultSize: { w: 600, h: 400 },
    defaultConfig: {
      url: '',
      title: 'Page Web',
      scale: 100,
      scroll: false,
      background: '#ffffff',
    },
    configSchema: [
      { key: 'url', type: 'text', label: 'URL', placeholder: 'https://...' },
      { key: 'title', type: 'text', label: 'Titre' },
      { key: 'scale', type: 'slider', label: 'Zoom (%)', min: 25, max: 150, step: 5 },
      { key: 'scroll', type: 'boolean', label: 'Autoriser le scroll' },
      { key: 'background', type: 'color', label: 'Fond' },
    ]
  },
  {
    type: 'playlist',
    label: 'Playlist',
    icon: ListVideo,
    description: 'Séquence de contenus avec minutage',
    defaultSize: { w: 640, h: 400 },
    defaultConfig: {
      items: [],
    },
    configSchema: [], // custom UI in WidgetConfig
  },
  {
    type: 'breaking-news',
    label: 'Breaking News',
    icon: Zap,
    description: 'Popup actualité style TV info — alimenté par RSS',
    defaultSize: { w: 900, h: 130 },
    defaultConfig: {
      feedUrl: '',
      label: 'FLASH',
      labelColor: '#ef4444',
      backgroundColor: '#ffffff',
      textColor: '#111111',
      displaySeconds: 12,
      pauseSeconds: 8,
      refreshMinutes: 10,
    },
    configSchema: [
      { key: 'feedUrl', type: 'text', label: 'URL du flux RSS', placeholder: 'https://feeds.lemonde.fr/rss/une' },
      { key: 'label', type: 'text', label: 'Label (ex: FLASH, BREAKING, ACTUALITÉ)' },
      { key: 'labelColor', type: 'color', label: 'Couleur du badge' },
      { key: 'backgroundColor', type: 'color', label: 'Fond de la carte' },
      { key: 'textColor', type: 'color', label: 'Couleur du titre' },
      { key: 'displaySeconds', type: 'slider', label: 'Durée d\'affichage (sec)', min: 5, max: 30, step: 1 },
      { key: 'pauseSeconds', type: 'slider', label: 'Pause entre deux news (sec)', min: 3, max: 60, step: 1 },
      { key: 'refreshMinutes', type: 'number', label: 'Rafraîchir le flux (min)', min: 1 },
    ]
  },
  {
    type: 'ticketing',
    label: 'Ticketing',
    icon: Ticket,
    description: 'Liste de tickets CRM / support live',
    defaultSize: { w: 420, h: 500 },
    defaultConfig: {
      datasourceId: null,
      itemsPath: '',
      fieldTitle: 'title',
      fieldStatus: 'status',
      fieldPriority: 'priority',
      fieldAssignee: 'assignee',
      fieldId: 'id',
      maxItems: 20,
      accentColor: '#6366f1',
      headerTitle: 'Tickets',
      showHeader: true,
      autoScroll: true,
      scrollSpeed: 40,
      refresh_s: 30,
    },
    configSchema: [
      { key: 'headerTitle', type: 'text', label: 'Titre du panneau' },
      { key: 'showHeader', type: 'boolean', label: 'Afficher le header' },
      { key: 'accentColor', type: 'color', label: 'Couleur accent' },
      { key: 'itemsPath', type: 'text', label: 'Chemin vers le tableau (ex: data.results)', placeholder: 'data.results' },
      { key: 'fieldTitle', type: 'text', label: 'Champ titre', placeholder: 'title' },
      { key: 'fieldStatus', type: 'text', label: 'Champ statut', placeholder: 'status' },
      { key: 'fieldPriority', type: 'text', label: 'Champ priorité', placeholder: 'priority' },
      { key: 'fieldAssignee', type: 'text', label: 'Champ assigné', placeholder: 'assignee' },
      { key: 'fieldId', type: 'text', label: 'Champ ID', placeholder: 'id' },
      { key: 'maxItems', type: 'number', label: 'Nombre max de tickets', min: 1, max: 100 },
      { key: 'autoScroll', type: 'boolean', label: 'Défilement automatique' },
      { key: 'scrollSpeed', type: 'slider', label: 'Vitesse défilement (px/s)', min: 5, max: 120, step: 5 },
      { key: 'refresh_s', type: 'number', label: 'Refresh UI (secondes)', min: 10 },
    ],
  },
]

export function getWidgetInfo(type) {
  return WIDGET_CATALOG.find(w => w.type === type)
}

export function getLucideIcon(type) {
  const widget = getWidgetInfo(type)
  return widget?.icon
}
